### PR TITLE
Update contributor guidelines

### PR DESCRIPTION
**Pull request by SultanOrazbayev**
Follows up on https://github.com/python-graphblas/python-graphblas/issues/198.

This is based on the guidelines of:

- networkx: https://github.com/networkx/networkx/blob/main/CONTRIBUTING.rst

Work in progress (only some sections are added).

### CODE REVIEW

**Comment by jim22k** [comment]
Changes discussed in the meeting:

- Make commands (git clone) look like code
- Remove networkx reference ("Navigate to the folder networkx...)
- Create a dev-requirements.txt file in the repo
- Update pip instructions to point to dev-requirements.txt (not the networkx versions)
- Update `pip install -e .` to `pip install -e . --no-deps`
- Remove "PYTHONPATH=." from pytest command

**Comment by eriknw** [comment]
Also, please be sure to add a simple `CONTRIBUTING.md` file that points to the "contributing" section of the docs. For example, here is `CONTRIBUTING.md` from dask: https://github.com/dask/dask/blob/main/CONTRIBUTING.md

**Comment by SultanOrazbayev** [comment]
Build of the docs is failing right now due to a missing `conf.py` file.

**Comment by SultanOrazbayev** [comment]
Current status:

- [x] Make commands (git clone) look like code
- [x] Remove networkx reference ("Navigate to the folder networkx...)
- [ ] Create a dev-requirements.txt file in the repo
- [ ] Update pip instructions to point to dev-requirements.txt (not the networkx versions)
- [x] Update pip install -e . to pip install -e . --no-deps
- [x] Remove "PYTHONPATH=." from pytest command

**Comment by SultanOrazbayev** [comment]
I tried following the instructions for `pip`-based installation on an Ubuntu machine with Python 3.9.7, but on step

```shell
pip install -r dev-requirements.txt
```
I get an error:

> ERROR: Could not find a version that satisfies the requirement python-suitesparse-graphblas (from versions: none)
> ERROR: No matching distribution found for python-suitesparse-graphblas

Not sure how to handle this. @eriknw @jim22k

**Comment by SultanOrazbayev** [comment]
Sorry, false alarm it seems, if I understand correctly, the `pip` version is this https://pypi.org/project/suitesparse-graphblas/

**Comment by eriknw** [comment]
heh, yup--and a perfect example of why it would be nice to have `dev-requirements.txt` ;)

**Comment by SultanOrazbayev** [comment]
OK, I managed to install everywithin with `pip` and run the tests. One of the the tests is failing `test_version` in `tests/test_core.py` due to a mismatch in the hardcoded version in the test and the fact that the local version is installed using `pip install -e . --no-deps`. I guess it's a minor issue related to tests, so hopefully the guidelines are good to go.

**Comment by eriknw** [comment]
>  One of the the tests is failing test_version in tests/test_core.py

Interesting. What is `graphblas.__version__` in your environment?

**Comment by SultanOrazbayev** [comment]
I don’t have access to the computer now (sending from a phone), but it was
something that ended with “.dirty” and a bunch of chars (some hash maybe).
I will post tomorrow.

**Review by jim22k — APPROVED** [review]

**Comment by jim22k** [comment]
@SultanOrazbayev Thanks for putting this together and testing it out!

**Comment by eriknw** [comment]
> One of the the tests is failing test_version in tests/test_core.py

btw, I was able to follow the instructions here (including downloading the repo) to make a Python virtual environment and everything worked! `graphblas.__version__` was correct for me (having `"dirty"` at the end is expected) and all tests pass :tada:

Thanks again @SultanOrazbayev :tada:

**Comment by SultanOrazbayev** [comment]
Interesting, maybe it's because the PR was merged... My old repo still shows the assertion error.

image

**Pull request merged**
